apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"sonarqube"},"name":"sonarqube-pvc","namespace":"sonarqube"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"sonarqube-sc","volumeName":"sonarqube-pv"}}
  creationTimestamp: '2025-04-03T11:43:11Z'
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: sonarqube
  name: sonarqube-pvc
  namespace: sonarqube
  resourceVersion: '4094965'
  uid: f3a89b68-e664-40e7-bede-b4ecddb83cca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sonarqube-sc
  volumeMode: Filesystem
  volumeName: sonarqube-pv
status:
  phase: Pending
