apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube  # Ensure it's in the correct namespace
spec:
  type: LoadBalancer  # ✅ Changed from ClusterIP to LoadBalancer
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: sonarqube  # Ensure PostgreSQL is in the same namespace
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
