apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-extension-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sonarqube-extension-sc
  hostPath:
    path: "/mnt/data/sonarqube-extension"
