apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-logs-pvc
  namespace: sonarqube
  labels:
    app.kubernetes.io/name: sonarqube-logs
    app.kubernetes.io/instance: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: sonarqube-sc
  volumeMode: Filesystem
