apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sonarqube-sc
provisioner: kubernetes.io/no-provisioner  # No dynamic provisioning
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
